Face and Car Number Plate Detection using OpenCV

In [1]:
import cv2
import matplotlib.pyplot as plt
import os
import glob
import numpy as np

In [22]:
img = cv2.imread('sample.jpg')
img = cv2.resize(img, (300,300))
#img = cv2.rotate(img, cv2.cv2.ROTATE_90_CLOCKWISE)

In [23]:
cv2.imshow('Image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [28]:
print(img[100])

[[164 188 216]
 [164 188 216]
 [166 190 218]
 ...
 [ 94 104 122]
 [ 92 104 122]
 [ 91 103 121]]


In [6]:
#cv2.imwrite('new_img.jpg', img)

True

In [7]:
#img2 = cv2.imread('new_img.jpg')
#cv2.imshow('Image', img2)
#cv2.waitKey(0)
#cv2.destroyAllWindows()

In [24]:
#coverting to gray scale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [25]:
cv2.imshow('Image', gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [26]:
# load the Frontalface and number plate pre-trained detector from CV2
n_face_detector = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
#n_number_detector = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_russian_plate_number.xml')

In [27]:
# detect the face and number plates in the grayscale image
#detections = n_plate_detector.detectMultiScale(gray, scaleFactor=1.3, minNeighbors=5)
detections = n_face_detector.detectMultiScale(gray, scaleFactor=1.3, minNeighbors=5)

In [28]:
detections

array([[ 53, 106,  90,  90]])

In [29]:
# loop over the face/number plate bounding boxes
for (x, y, w, h) in detections:
    # draw a rectangle around the number plate
    cv2.rectangle(img, (x, y), (x + w, y + h), (0, 255, 255), 2)
    cv2.putText(img, "human detected", (x - 20, y - 10),
    cv2.FONT_HERSHEY_COMPLEX, 0.5, (0, 255, 255), 2)

In [30]:
# extract the face/number plate from the grayscale image
#number_plate = gray[y:y + h, x:x + w]

face = gray[y:y + h, x:x + w]

#tag = img[500:700, 600:900] -- copy 500 to 700 rows, pick 600 to 900 columns
#img[100:300, 650:950] = tag -- paste to 100:300 rows, and 650 to 950 columns

In [31]:
cv2.imshow("Face", face)

cv2.imshow("Face detection", img)
cv2.waitKey(0)

-1

In [32]:
#write/save the detected image
cv2.imwrite('sample.jpg', img)

True